version: '3'

services:
  api:
    container_name: api_strapi_mysql
    depends_on:
      - db
    image: strapi/strapi
    restart: unless-stopped
    environment:
      APP_NAME: strapi-app
      DATABASE_CLIENT: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: db_strapi
      DATABASE_USERNAME: my_user
      DATABASE_PASSWORD: my_password
      DATABASE_SSL: "false"
    ports: 
      - 8080:8080
    volumes:
      - C:/srv/strapi:/usr/src/api/strapi-app

  db:
    container_name: db_strapi_mysql
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_strapi
      MYSQL_USER: user
      MYSQL_PASSWORD: password
